
(function($){var mouseTracker=function(){var regions=[];var cursor=null;var intersectsAnyRegion=function(bounds){for(var reg=0;reg<regions.length;reg++){for(var i=0;i<regions[reg].rects.length;i++){var r=regions[reg].rects[i];var disparate=bounds[0]>r[0]+r[2]||r[0]>bounds[0]+bounds[2]||bounds[1]>r[1]+r[3]||r[1]>bounds[1]+bounds[3];if(!disparate)return true;}}
return false;};$(document).ready(function(){$(document).mousemove(function(e){for(var i=0;i<regions.length;i++){var r=regions[i];var inside=$.grep(r.rects,function(n){return e.pageX>=n[0]&&e.pageY>=n[1]&&e.pageX<=n[0]+n[2]&&e.pageY<=n[1]+n[3];}).length>0;if(r.inside!==null&&inside&&!r.inside&&r.mouseEnter){r.mouseEnter(r.backing);}else if(r.inside!==null&&!inside&&r.inside&&r.mouseLeave){r.mouseLeave(r.backing);}
r.inside=inside;}});});return{add:function(rectsArray,backing,options){var r={rects:rectsArray,inside:options.inside,backing:backing,enabled:true,solid:options.solidRectangle};if(options.mouseEnter)r.mouseEnter=options.mouseEnter;if(options.mouseLeave)r.mouseLeave=options.mouseLeave;regions.push(r);return r;},remove:function(region){for(var i=0;i<regions.length;i++){if(regions[i]===region){regions.splice(i,1);return;}}},anyPopoverIntersects:function(bounds,skipSolid){for(var reg=0;reg<regions.length;reg++){if(regions[reg].rects){var r=regions[reg].rects[0];if(skipSolid!==true||!r.solid){var disparate=bounds[0]>r[0]+r[2]||r[0]>bounds[0]+bounds[2]||bounds[1]>r[1]+r[3]||r[1]>bounds[1]+bounds[3];if(!disparate)return true;}}}
return false;}};}();var iframePool=function(){var HTML='<iframe frameborder="0" tabindex="-1" src="/js/lib/popover/iframe.html" style="display:none;position:absolute;z-index:0;filter:Alpha(Opacity=\'0\');opacity:0;" />';var availIframes=[];var addToLib=function(n){for(i=0;i<n;i++){var iframe=$(HTML);iframe.prependTo(document.body);availIframes.push(iframe);}};$(document).ready(function(){addToLib(6);});return{checkout:function(jqObj){if(availIframes.length<=0)addToLib(1);var iframe=availIframes.pop();iframe.css({display:'block',top:jqObj.offset().top,left:jqObj.offset().left,width:jqObj.outerWidth(),height:jqObj.outerHeight()});return iframe;},checkin:function(iframe){iframe.css({display:'none'});availIframes.push(iframe);}};}();var elementHidingManager=function(){var win=/Win/.test(navigator.platform);var mac=/Mac/.test(navigator.platform);var linux=/Linux/.test(navigator.platform);var version=parseInt($.browser.version);var hiddenElements=[];var hideIfIntersects=function(obj){var alwaysShow=typeof(goN2Events)!="undefined"&&goN2Events._toggleControlElements&&goN2Events._toggleControlElements[obj.attr('id')]=='alwaysShow';var po=obj.attr('id')&&obj.attr('id').substring(0,4)=='_po_'||obj.attr('name')&&obj.attr('name').substring(0,4)=='_po_';if(!alwaysShow&&!po){if(obj.css("visibility")!="hidden"){var bounds=[obj.offset().left,obj.offset().top,obj.outerWidth(),obj.outerHeight()];if(mouseTracker.anyPopoverIntersects(bounds,$.browser.msie&&version==7)){hiddenElements.push([obj,bounds]);obj.css("visibility","hidden");}}}};return{update:function(solidRectangle){var stillHidden=[];for(var i=0;i<hiddenElements.length;i++){if(mouseTracker.anyPopoverIntersects(hiddenElements[i][1],$.browser.msie&&version==7)){stillHidden.push(hiddenElements[i]);}else{hiddenElements[i][0].css("visibility","visible");}}
hiddenElements=stillHidden;var canOverlayWmodeWindow=$.browser.mozilla&&$.browser.version.indexOf("1.9.")==0&&mac||$.browser.safari&&version>=522&&version<=525&&mac||$.browser.mozilla&&$.browser.version=="1.8.1"&&linux;$("object,embed").each(function(){var obj=$(this);var wmode=obj.is("embed")?obj.attr("wmode"):obj.children("embed").attr("wmode");if(typeof wmode=="undefined")wmode="window";if(wmode=="window"&&!canOverlayWmodeWindow){hideIfIntersects(obj);}});if($.browser.safari&&/Windows/.test(window.navigator.userAgent)){$("iframe").each(function(){var obj=$(this);hideIfIntersects(obj);});}
if(typeof(goN2Events)!='undefined'){for(element in goN2Events._toggleControlElements){if(goN2Events._toggleControlElements[element]!='alwaysShow'){$('#'+element).each(function(){var obj=$(this);hideIfIntersects(obj);});}}}}};}();var applyBacking=function(popover,options){var region=null;var iframe=null;options=options||{};var destroy=function(){if(region){mouseTracker.remove(region);region=null;}
if(iframe){iframePool.checkin(iframe);iframe=null;}
elementHidingManager.update();};var disable=function(){if(iframe)iframe.hide();if(region)region.enabled=false;elementHidingManager.update();};var enable=function(){if(iframe)iframe.show();if(region)region.enabled=true;elementHidingManager.update();};var refreshBounds=function(){if($.browser.msie && parseInt($.browser.version) < 7) popover.find('.ap_body .ap_left:first, .ap_body .ap_right:first').css('height', popover.find('.ap_body:first').height() + 'px');var newBounds=[popover.offset().left,popover.offset().top,popover.outerWidth(),popover.outerHeight()];if(region){region.rects[0]=newBounds;}
if(iframe)iframe.css({left:newBounds[0],top:newBounds[1],width:newBounds[2],height:newBounds[3]});elementHidingManager.update();}
var backing={destroy:destroy,popoverObject:popover,refreshBounds:refreshBounds,enable:enable,disable:disable}
var bounds=[];bounds.push([popover.offset().left,popover.offset().top,popover.outerWidth(),popover.outerHeight()]);if(options.additionalCursorRects){for(var i=0;i<options.additionalCursorRects.length;i++){bounds.push(options.additionalCursorRects[i]);}}
region=mouseTracker.add(bounds,backing,options);/*$('input:text').blur();*/iframe=iframePool.checkout(popover);elementHidingManager.update();popover.backing=backing;return backing;};$.fn.initAmazonPopover=function(customSettings){var settings=customSettings||{};var trigger=this;var popover=null;initialize();if(!settings.showOnHover)this.mouseover(preparePopover);if(!settings.localContent&&!settings.destination&&!settings.literalContent&&trigger.attr("href")){settings.destination=trigger.attr("href");}
if(settings.showOnHover===true){var timerID=null;trigger.mouseover(function(e){if((!popover||!popover.is(":visible"))&&!timerID){timerID=setTimeout(function(){if(popover){popover.show();if(popover.backing)popover.backing.enable();if(settings.onShow)settings.onShow.call(trigger);}else{popover=displayPopover(settings,trigger,function(){popover=null;});}
timerID=null;},settings.hoverShowDelay);}
return false;});this.mouseout(function(e){if((!popover||!popover.is(":visible"))&&timerID){clearTimeout(timerID);timerID=null;}});}else{trigger.click(function(e){if(popover&&popover.is(":visible")){popover.destroy();popover=null;}else{if(popover){popover.show();if(popover.backing)popover.backing.enable();if(settings.onShow)settings.onShow.call(trigger);}else{popover=displayPopover(settings,trigger,function(){popover=null;});}}
return false;});}
return this;};var displayPopover=function(customSettings,trigger,destroyFunction){var settings=$.extend({},$.AmazonPopover.defaultSettings,customSettings);if(!settings.locationFunction){settings.locationFunction=settings.modal||settings.centered||!trigger?getModalLocation:getPopoverLocation;}
if(settings.showCloseButton===null){settings.showCloseButton=!settings.showOnHover;}
var hide=function(){if(settings.skin===null){popover.hide();if(popover.backing)popover.backing.disable();}else{popover.remove();if(destroyFunction)destroyFunction();if(settings.onDestroy)settings.onDestroy();if(popover.backing)popover.backing.destroy();}
$('#ap_overlay').remove();$(document).unbind('scroll.AmazonPopover');if(settings.onHide){settings.onHide.call(trigger);}
return false;};if(settings.skin===null){var popover=$(settings.localContent).prependTo(document.body);}else if(settings.skin=="default"){preparePopover();var popover=$.AmazonPopover.preparedPopover;$('body').append(popover);}else{var skinIsHtml=/^[^<]*(<(.|\s)+>)[^>]*$/.test(settings.skin);var skin=(skinIsHtml?settings.skin:$.AmazonPopover.skins[settings.skin])||$.AmazonPopover.skins["default"];var popover=$(skin);$('body').append(popover);}
var location=settings.locationFunction(settings,trigger);popover.css({top:location.top,left:location.left,margin:location.margin,right:location.right,zIndex:settings.zIndex,position:"absolute"});if(settings.width){popover.css("width",settings.width);}
if(settings.followScroll){$(document).bind('scroll.AmazonPopover',function(e){followScroll(e);});}
if(popover.ifixpng)popover.ifixpng();if($.browser.msie&&parseInt($.browser.version)<7)popover.find("*").each(function(){var bi=$(this).css('background-image');if(bi.indexOf(".png")!=-1){var iebi=bi.split('url("')[1].split('")')[0];$(this).css('background-image','none');$(this).get(0).runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+iebi+"',sizingMethod='scale')";}});popover.show();if(settings.onShow){settings.onShow.call(trigger);}
if(settings.onCreate){settings.onCreate.call(trigger);}
if(settings.title){popover.find('.ap_title').html(settings.title);var titleBar=popover.find('.ap_titlebar');var contentTopPad=titleBar.height()-7;if(settings.skin=="default"||settings.skin=="alert"){titleBar.css({width:(settings.width-36)+'px'});popover.find('.ap_content').css({paddingTop:contentTopPad+'px'});}
if(settings.draggable&&!settings.modal){enableDragAndDrop2(titleBar,popover);}
titleBar.show();}else{popover.find('.ap_titlebar').hide();}
if(settings.showCloseButton!==false){popover.find('.ap_close').show().click(hide).mousedown(function(e){e.preventDefault();e.stopPropagation();return false;}).css("cursor","default");}else{popover.find('.ap_close').hide();}
if(settings.closeText){popover.find('.ap_closetext').text(settings.closeText).show();}
if(skin!==null){var container=popover.find('.ap_content');var popoverContent;if(settings.destination){popoverContent=$.AmazonPopover.ajaxCache[settings.destination];}else if(settings.localContent){popoverContent=$(settings.localContent).clone(true).show();}else if(settings.literalContent){popoverContent=settings.literalContent;}
if(popoverContent)container.html(popoverContent);}
popover.find('.ap_custom_close').click(hide);$.AmazonPopover.preparedPopover=null;if(settings.showOnHover){var timerID=null;applyBacking(popover,{solidRectangle:settings.solidRectangle,mouseEnter:function(backing){if(timerID){clearTimeout(timerID);timerID=null;}},mouseLeave:function(){if(timerID)clearTimeout(timerID);timerID=setTimeout(function(){hide();timerID=null;},settings.hoverHideDelay);},additionalCursorRects:trigger?[[trigger.offset().left,trigger.offset().top,trigger.outerWidth(),trigger.outerHeight()]]:[],inside:true});}else{applyBacking(popover,{solidRectangle:settings.solidRectangle});}
fillPopover(popover,settings);if(settings.modal){var overlay=$('<div id="ap_overlay"/>');overlay.css((settings.modalContent)?{width:$(settings.modalContent).width(),height:$(settings.modalContent).height(),left:$(settings.modalContent).offset().left+'px',top:$(settings.modalContent).offset().top+'px',backgroundColor:'#FFF'}:{width:getPageWidth(),height:getPageHeight(),position:($.browser.mozilla||$.browser.safari)?'fixed':'',opacity:0.4});overlay.appendTo(document.body);if(settings.modalFadeSpeed <= 0)overlay.show(); else overlay.fadeIn(settings.modalFadeSpeed);}
popover.destroy=hide;return popover;};var fillPopover=function(popover,settings){if(settings.destination&&!$.AmazonPopover.ajaxCache[settings.destination]){var container=popover.find('.ap_content');$.get(settings.destination,function(data,status){$.AmazonPopover.ajaxCache[settings.destination]=data;container.hide();container.html(data);if($.browser.msie && parseInt($.browser.version) < 7) { container.css('display', ''); popover.backing.refreshBounds(); } else container.slideDown(function(){popover.backing.refreshBounds();});});}if($.browser.msie && parseInt($.browser.version) < 7) popover.find('.ap_body .ap_left:first, .ap_body .ap_right:first').css('height', popover.find('.ap_body:first').height() + 'px');}
var getPageWidth=function(){return $.browser.msie?$(document).width()+'px':'100%';};var getPageHeight=function(){return $.browser.msie?$(document).height()+20+'px':'100%';};var getPopoverLocation=function(settings,trigger){var triggerLocation=trigger.offset();return{left:triggerLocation.left+'px',top:(triggerLocation.top+$(trigger).height())+'px',margin:'0px'};};var getModalLocation=function(settings){var y=$(window).scrollTop()+100;return{left:-(settings.width/2)+'px',right:'0px',top:y+'px',margin:'0% 50%'};};var initialize=function(){if($.AmazonPopover.initialized)return;$.AmazonPopover.initialized=true;if($.browser.msie){$(window).resize(function(){$('#ap_overlay').css({width:getPageWidth(),height:getPageHeight()});});}};var preparePopover=function(){if(!$.AmazonPopover.preparedPopover){var popover=$($.AmazonPopover.skins["default"]);popover.css({top:'-2000px',left:'-2000px'});$('body').append(popover);$.AmazonPopover.preparedPopover=popover;}};var enableDragAndDrop2=function(titlebar,popover){titlebar.css('cursor','move');disableSelect(popover.get(0));titlebar.mousedown(function(e){e.preventDefault();disableSelect(document.body);var offset=[e.pageX-popover.offset().left,e.pageY-popover.offset().top];var mousemove=function(e){e.preventDefault();popover.css({left:e.pageX-offset[0],top:e.pageY-offset[1]});};var mouseup=function(e){enableSelect(document.body);$(document).unbind("mousemove",mousemove);$(document).unbind("mouseup",mouseup);};$(document).mousemove(mousemove).mouseup(mouseup);});}
var enableDragAndDrop=function(titleBar){titleBar.css('cursor','move');titleBar.mousedown(function(e){var parent=$(this).parent();$.AmazonPopover.draggedElement=parent;disableSelect(document.body);disableSelect(parent[0]);$.AmazonPopover.mouseStart={x:e.pageX-$(this).offset().left,y:e.pageY-$(this).offset().top};$().bind('mousemove.popover',function(e){var start=$.AmazonPopover.mouseStart;if(start){var x=e.pageX-start.x-15;var y=e.pageY-start.y-10;var elem=$.AmazonPopover.draggedElement;if(elem){elem.css({top:y+'px',left:x+'px'});}}});$().one('mouseup.popover',function(e){enableSelect(document.body);enableSelect(parent[0]);$().unbind('mousemove.popover');});});};var disableSelect=function(e){if(e){e.onselectstart=function(e){return false;};e.style.MozUserSelect='none';}};var enableSelect=function(e){if(e){e.onselectstart=function(e){return true;};e.style.MozUserSelect='';}};var followScroll=function(e){var popover=$('.ap_popover');var height=popover.height();var top=popover.position().top;var bottom=top+height;var scrollTop=$(document).scrollTop();var scrollBottom=scrollTop+$(window).height();var PADDING=99;if(scrollTop<top-PADDING){popover.css({'position':'fixed','top':PADDING+'px'});$.AmazonPopover.pinned='top';}else if(scrollBottom>bottom+PADDING){popover.css({'position':'fixed','top':($(window).height()-height-PADDING)+'px'});$.AmazonPopover.pinned='bottom';}
if(scrollTop<=$.AmazonPopover.lastScrollTop&&$.AmazonPopover.pinned=='bottom'||scrollTop>=$.AmazonPopover.lastScrollTop&&$.AmazonPopover.pinned=='top'){popover.css({'position':'absolute','top':top+'px'});$.AmazonPopover.pinned=null;}
$.AmazonPopover.lastScrollTop=scrollTop;};$.AmazonPopover={initialized:false,defaultSettings:{width:500,destination:null,localContent:null,literalContent:null,followScroll:false,locationFunction:null,modal:false,modalContent:null,modalFadeSpeed:500,centered:false,draggable:false,closeText:'',showCloseButton:null,zIndex:100,showOnHover:false,hoverShowDelay:200,hoverHideDelay:200,skin:"default"},ajaxCache:{},preparedPopover:null,lastScrollTop:0,pinned:null,dragegedElement:null,mouseStart:null,mouseOffset:null,displayPopover:displayPopover,skins:{"default":'<div class="ap_popover"> \
                    <div class="ap_header"> \
                        <div class="ap_left"/> \
                        <div class="ap_middle"/> \
                        <div class="ap_right"/> \
                    </div> \
                    <div class="ap_body"> \
                        <div class="ap_left"/> \
                        <div class="ap_content"><img src="https://images-na.ssl-images-amazon.com/images/G/01/javascripts/lib/popover/images/snake.gif"/></div> \
                        <div class="ap_right"/> \
                    </div> \
                    <div class="ap_footer"> \
                        <div class="ap_left"/> \
                        <div class="ap_middle"/> \
                        <div class="ap_right"/> \
                    </div> \
                    <div class="ap_titlebar"> \
                        <div class="ap_title"/> \
                    </div> \
					<div class="ap_close"><a href="#"><span class="ap_closetext"/><span class="ap_closebutton"><span></span></span></a></div> \
                    </div>',
                    "alert":'<div class="ap_popover ap_alert"> \
                    <div class="ap_header"> \
                    <div class="ap_left"/> \
                    <div class="ap_middle"/> \
                    <div class="ap_right"/> \
                    </div> \
                    <div class="ap_body"> \
                    <div class="ap_left"/> \
                    <div class="ap_icon_alert"/> \
                    <div class="ap_content"><img src="https://images-na.ssl-images-amazon.com/images/G/01/javascripts/lib/popover/images/snake.gif"/></div> \
                    <div class="ap_right"/> \
                    </div> \
                    <div class="ap_footer"> \
                    <div class="ap_left"/> \
                    <div class="ap_middle"/> \
                    <div class="ap_right"/> \
                    </div> \
                    <div class="ap_titlebar"> \
                    <div class="ap_title"/> \
                    </div> \
                    <div class="ap_close"><a href="#"><span class="ap_closetext"/><span class="ap_closebutton"><span></span></span></a></div> \
                    </div>',
                    "classic":'<div style="border-top:1px solid #ccc;border-left:1px solid #ccc;border-bottom:1px solid #2F2F1D; border-right:1px solid #2F2F1D;background-color:#EFEDD4;padding:3px;"> \
                    <div style="color:#86875D;font-size:12px;padding:0 0 0 0;line-height:1em;" class="ap_titlebar"> \
                        <div class="ap_close" style="float:right"> \
                            <img width="46" height="16" border="0" alt="close" onmouseup=\'this.src="https://images-na.ssl-images-amazon.com/images/G/01/nav2/images/close-tan-sm._V46903531_.gif";\' onmouseout=\'this.src="https://images-na.ssl-images-amazon.com/images/G/01/nav2/images/close-tan-sm._V46903531_.gif";\' onmousedown=\'this.src="https://images-na.ssl-images-amazon.com/images/G/01/nav2/images/close-tan-sm-dn._V46881222_.gif";\' src="https://images-na.ssl-images-amazon.com/images/G/01/nav2/images/close-tan-sm._V46903531_.gif" /> \
                        </div> \
                        <span class="ap_title" style="padding:0;"></span> \
                    </div> \
                    <div class="ap_content" style="clear:both;background-color:white;border:1px solid #ACA976;padding:8px;font-size:11px;"></div> \
                </div>'}};$(document).ready(function(){$('a[role^="AmazonPopover"]').initAmazonPopover();});})(jQuery)