(window.AmazonUIPageJS?AmazonUIPageJS:P).execute(function(){ASPP.when("ASPA","augur-utils").execute(function(d,b){d.declarative("augur-fsl-increase-storage","click",function(a){$("#augur_fsl_current_usage_stats .asp-declarative").attr("data-action","");$("#augur_fsl_popover_loading").removeClass("asp-hidden");var c=d.state(a.data.workflowName+"_state");b.setIntoState(c,b.getWevObjectTypeName(),a.data.outputKey,a.data.storageType);b.getNextNode(a.data.workflowId,a.data.currentNodeId,c,a.data.updatingDivId);
b.getMetricsHandle(c)("storageIncrementRequest",{storageType:a.data.storageType})})});ASPP.when("ASPA","spaui-external-metrics").register("augur-utils",function(d,b){var a=d.$,c={getNextNode:function(f,b,g,e){var h=g?c.getMetricsHandle(g):!1,g=g?c.jsonStringify(g):"";d.post("/hz/augur/execute-workflow",{params:{workflowId:f,currentNodeId:b,state:g},success:function(f){if(e&&e.toUpperCase()!=="NONE"){a("#"+e).html("");var c=a("<div />");c.html(f);c.find(".augur-workflow-error").length!==0?(a("#"+e).html(f),
h&&h("getNextWorkflowNodeError",{currentNodeId:b})):(c.children().each(function(){var f=a(this).attr("augur-wf-append-to");a(this).children().each(function(){this.id!==null&&this.id!==""&&a("#"+f).find("#"+this.id).remove()});a("#"+f).append(a(this).html());a(this).remove()}),h&&h("getNextWorkflowNodeSuccess",{currentNodeId:b}))}},error:function(){e&&e.toUpperCase()!=="NONE"&&(a("#"+e).html("<b>We are facing some technical issues as of now, please try again later.<b>"),h&&h("getNextWorkflowNodeFatal",
{currentNodeId:b}))},timeout:8E4})},jsonStringify:function(a){return window.JSON&&JSON.stringify?JSON.stringify(a):c.mapToString(a)},mapToString:function(a){var b="{",g=0;if(a!==null)for(var e in a)a.hasOwnProperty(e)&&(g!==0&&(b+=", "),b+='"'+e+'":"'+c.escapeJson(a[e])+'"',g++);b+="}";return b},escapeJson:function(a){var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f",
"\r":"\\r",'"':'\\"',"\\":"\\\\"};b.lastIndex=0;return a.replace(b,function(a){return c[a]?c[a]:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})},getWevObjectTypeName:function(){return"workflow_execution_variables"},setIntoState:function(a,b,c,e){for(var d=0;d<a.racerXObjects.length;d++)a.racerXObjects[d].objectType===b&&(a.racerXObjects[d].attributes[c]=e)},getMetricsHandle:function(a){for(var d,g,e=0;e<a.racerXObjects.length;e++)if(a.racerXObjects[e].objectType===c.getWevObjectTypeName())d=
a.racerXObjects[e].attributes.client,g=a.racerXObjects[e].attributes.workflow_execution_id;if(d&&g)return b.register(g,d);else console.error("[AugurUI] Client name or WorkflowExecutionId cannot be null or empty.")}};return c});ASPP.when("ASPA","augur-utils").execute(function(d,b){d.declarative("augur_wd_check_asin_fnsku","click",function(a){$("#augur_wd_submit .asp-declarative").attr("data-action","");$("#augur_wd_popover_loading").removeClass("asp-hidden");var c=d.state(a.data.workflowName+"_state"),
f=$("#"+a.data.textInputId).val(),f=f.trim();b.setIntoState(c,b.getWevObjectTypeName(),a.data.outputKey,f);b.getNextNode(a.data.workflowId,a.data.currentNodeId,c,a.data.updatingDivId);b.getMetricsHandle(c)("asinFnskuInputByMerchant",{textInputValue:f})});d.declarative("augur_wd_check_case_details","click",function(a){$("#augur_wd_done .asp-declarative").attr("data-action","");$("#augur_wd_popover_loading").removeClass("asp-hidden");var c=d.state(a.data.workflowName+"_state"),f=$("#"+a.data.caseDetailsInputId).val();
b.setIntoState(c,b.getWevObjectTypeName(),a.data.outputKey,f);b.getNextNode(a.data.workflowId,a.data.currentNodeId,c,a.data.updatingDivId);b.getMetricsHandle(c)("caseDetailsInputByMerchant",{caseDetailsInputValue:f})});d.declarative("augur_wd_radio_fnsku_selected","click",function(a){$("#augur_wd_next .asp-declarative").attr("data-action","");$("#augur_wd_popover_loading").removeClass("asp-hidden");var c=d.state(a.data.workflowName+"_state"),f=$("input[name=radioButtonSelectValue]").filter(":checked").val();
b.setIntoState(c,b.getWevObjectTypeName(),a.data.outputKey,f);b.getNextNode(a.data.workflowId,a.data.currentNodeId,c,a.data.updatingDivId);b.getMetricsHandle(c)("fnskuInputByMerchant",{fnskuInputValue:f})});d.declarative("augur_wd_radio_selected","click",function(){$("input[name=radioButtonSelectValue]").is(":checked")&&$("#augur_wd_next").removeClass("asp-hidden")});d.declarative("augur_wd_check_another_asin_fnsku","click",function(a){$("#augur_wd_popover_loading_link").removeClass("asp-hidden");
b.getNextNode(a.data.workflowId,"",null,a.data.updatingDivId)})})});